name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t assoc
    
    - name: Run image
      run: docker run assoc > answer_associativity_tmp.txt

    - name: Strip output
      run: tail -n 1 answer_associativity_tmp.txt > answer_associativity.txt
    
    - uses: actions/upload-artifact@v4
      with:
        name: assoc
        path: answer_associativity.txt

  push:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: dl code
          uses: actions/checkout@v4
        - name: dl result
          uses: actions/download-artifact@v4
          with:
            name: assoc
        - name: git config
          run: |
            git config --global user.name "CI-Auto"
            git config --global user.email "ci@auto.net"
        - name: push
          run: |
            git add answer_associativity.txt
            git commit -m "Upload result (CI)"
            git push
