name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t assoc

  execute:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Run image
      run: docker run assoc > answer_associativity.txt

  push:
      runs-on: ubuntu-latest
      needs: execute
      steps:
        - uses: actions/upload-artifact@v4
          with:
            name: assoc
            path: answer_associativity.txt
        - name: git conf
          run: |
            git config --global user.name "CI-Auto"
            git config --global user.email "ci@auto.net"
        - name: push
          run: |
            git add answer_associativity.txt
            git commit -m "Upload result (CI)"
            git push
