name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t assoc
    - run: docker run assoc >> output.txt
    - uses: actions/upload-artifact@v4
      with:
        name: assoc
        path: output.txt
    
